[project]
name = "actually_alright"
version = "0.1.0"
description = "A fork of the module alright, inteneded for Whatsapp automation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "selenium>=4.36.0",
]
